### ISSUE TITLE
addon引入问题，出现错误

### ISSUE THREAD

**Issue by ndaydayup** [grandpaxizhilang/WebCrawling#2]
**首先前提是都引入了addon.node文件**

**我使用node18版本执行vm.js文件：**
Error: The module '\\?\D:\Release\addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**怀疑是版本问题，更换到node20版本，虽然报的错误变了，但是不知道是什么情况**
TypeError [Error]: get_result is not a function
    at \WebCrawling\顶象滑块\js/NOWDEBUG.js:7297:1
    at Script.runInContext (node:vm:148:12)
    at VM.runScript (\WebCrawling\node_modules\vm2\lib\vm.js:288:18)
    at VM.run (\WebCrawling\node_modules\vm2\lib\vm.js:508:16)
    at get_result (\WebCrawling\顶象滑块\js\vm.js:23:20)
    at Object.<anonymous> (\WebCrawling\顶象滑块\js\vm.js:27:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)

Node.js v20.17.0

**Comment by grandpaxizhilang** [comment]
这个addon.node文件是用c++编译的插件，用来过 typeof documentall=="undefined"。
过顶象的话就可以删掉他，顶象他不检测这个

**Comment by ndaydayup** [comment]
throw bridge.from(e);
                                ^
TypeError [Error]: get_result is not a function
我尝试删除了documentall相关的引入以及方法，但是就出现了这样的错误，vm的js文件确实有这个方法，我也是执行的这个文件，node版本还是什么造成的嘛，因为我单纯执行js是没有问题的

**Comment by grandpaxizhilang** [comment]
在env.js文件里面的也有引用到documentall，这个可能需要找一下
然后env.js文件中有些环境参数我是删掉了，这个可能需要自己联调一下，看看那些环境还需要补充

**Comment by Walkerrrrrrrrrr** [comment]
感谢大佬，前面的错误就是env里面的也删除了才出现的这个错误，那一块我看你js中框起来了，我再看看
